#             _ _                  _    _
#   ___ _   _| | |_ _   _ _ __ ___| | _(_)_ __   __ _ ___
#  / __| | | | | __| | | | '__/ _ \ |/ / | '_ \ / _` / __|
# | (__| |_| | | |_| |_| | | |  __/   <| | | | | (_| \__ \
#  \___|\__,_|_|\__|\__,_|_|  \___|_|\_\_|_| |_|\__, |___/
#                                               |___/

version: 2
executorType: docker
containerInfo:
  - image: culturekings/php-ci
    env:
      - APP_ENV=local
      - APP_DEBUG=true
stages:
  build:
    workDir: /var/www/html
    steps:
      - type: checkout
      - type: shell
        name: Install Project Dependencies
        command: composer install -o --prefer-dist --no-interaction
      - type: shell
        name: Run Tests
        command: vendor/bin/phpspec run --format=pretty
      - type: shell
        name: Run Coding Standards
        command: |
          mkdir -p /tmp/testresults/phpcs
          vendor/bin/phpcs --config-set installed_paths vendor/culturekings/symfony2-coding-standard
          vendor/bin/phpcs --report-junit=/tmp/testresults/phpcs/junit.xml
      - type: shell
        name: Update Code Coverage
        command: |
          mkdir -p build/logs
          vendor/bin/coveralls -v -x coverage_clover.xml
      - type: test-results-store
        path: /tmp/testresults/
